services:
  dev-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '6.0'
          memory: 5G
        reservations:
          cpus: '3.0'
          memory: 2.5G